import { createEmptyEntry, normalizeTags } from "../schema.js";

export const PROVIDER_TEMPLATES = [
  {
    id: "google-analytics-4",
    name: "Google Analytics 4",
    provider: "Google",
    type: "Analytics",
    category: "Analytics and attribution",
    purpose: "Analytics collection",
    useCase: "Measure application traffic, content performance, campaigns, and conversion events.",
    riskLevel: "High",
    dashboardUrl: "https://analytics.google.com/",
    docsUrl: "https://developers.google.com/analytics",
    scopes: "GA4 property access, measurement protocol API secret, reporting API scopes as needed.",
    rotationCadence: "90 days",
    notes: "Record property ID, data streams, retention, consent mode, privacy notice, and who can access reports.",
    tags: ["google", "analytics", "privacy", "measurement"]
  },
  {
    id: "google-ads",
    name: "Google Ads",
    provider: "Google",
    type: "Ad platform",
    category: "Ads and monetization",
    purpose: "Ad serving or monetization",
    useCase: "Manage ad campaigns, conversion tracking, remarketing, and monetization workflows.",
    riskLevel: "Critical",
    dashboardUrl: "https://ads.google.com/",
    docsUrl: "https://developers.google.com/google-ads/api/docs/start",
    scopes: "Developer token, OAuth client, customer ID, conversion actions, billing-aware access.",
    rotationCadence: "90 days",
    notes: "Track developer token status, OAuth consent screen, billing owner, conversion tags, privacy purpose, and ad account access.",
    tags: ["google", "ads", "monetization", "oauth"]
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    provider: "Google Cloud",
    type: "Service account",
    category: "Cloud hosting",
    purpose: "Backend integration",
    useCase: "Connect applications to GCP services such as Secret Manager, Cloud Run, Maps, storage, or APIs.",
    riskLevel: "Critical",
    dashboardUrl: "https://console.cloud.google.com/",
    docsUrl: "https://cloud.google.com/docs/authentication",
    scopes: "Least-privilege IAM roles, service account key restrictions, workload identity where possible.",
    rotationCadence: "90 days",
    notes: "Prefer workload identity over downloadable JSON keys. Record project ID, service account, IAM roles, billing owner, and enabled APIs.",
    tags: ["gcp", "cloud", "service-account", "iam"]
  },
  {
    id: "github-app",
    name: "GitHub App or PAT",
    provider: "GitHub",
    type: "OAuth client",
    category: "Developer platform",
    purpose: "Automation workflow",
    useCase: "Automate repositories, issues, deployments, webhooks, package access, or CI/CD workflows.",
    riskLevel: "High",
    dashboardUrl: "https://github.com/settings/apps",
    docsUrl: "https://docs.github.com/en/apps",
    scopes: "Repository permissions, webhook secret, fine-grained token scopes, org installation boundaries.",
    rotationCadence: "90 days",
    notes: "Prefer GitHub Apps and fine-grained tokens. Record org owner, repo access, webhook target, and secret scanning posture.",
    tags: ["github", "automation", "repo", "webhook"]
  },
  {
    id: "openai",
    name: "OpenAI API",
    provider: "OpenAI",
    type: "AI model provider",
    category: "AI and machine learning",
    purpose: "Model inference",
    useCase: "Power application AI features, agents, structured extraction, embeddings, or internal automation.",
    riskLevel: "High",
    dashboardUrl: "https://platform.openai.com/",
    docsUrl: "https://platform.openai.com/docs",
    scopes: "Project-scoped API key, model access, budget limits, rate limits, data-handling notes.",
    rotationCadence: "90 days",
    notes: "Record project, budget owner, allowed use cases, data categories, logging policy, and abuse-monitoring path.",
    tags: ["ai", "llm", "openai", "budget"]
  },
  {
    id: "stripe",
    name: "Stripe",
    provider: "Stripe",
    type: "Payment processor",
    category: "Finance and payments",
    purpose: "Backend integration",
    useCase: "Accept payments, manage subscriptions, receive billing webhooks, and reconcile revenue events.",
    riskLevel: "Critical",
    dashboardUrl: "https://dashboard.stripe.com/",
    docsUrl: "https://docs.stripe.com/keys",
    scopes: "Restricted API keys, webhook signing secrets, live/test mode separation, billing admin access.",
    rotationCadence: "90 days",
    notes: "Separate test/live keys. Record webhook endpoints, signing secret, tax/billing owner, and incident path for payment failures.",
    tags: ["payments", "stripe", "billing", "webhook"]
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    provider: "Cloudflare",
    type: "API key",
    category: "Core infrastructure",
    purpose: "Backend integration",
    useCase: "Manage DNS, Workers, Pages, R2, KV, D1, tunnels, firewall, and edge infrastructure.",
    riskLevel: "Critical",
    dashboardUrl: "https://dash.cloudflare.com/",
    docsUrl: "https://developers.cloudflare.com/fundamentals/api/get-started/create-token/",
    scopes: "Scoped API token, account/zone boundaries, DNS/Workers/R2 permissions as needed.",
    rotationCadence: "90 days",
    notes: "Use scoped API tokens instead of global API keys. Record account ID, zone ID, token scopes, and emergency DNS owner.",
    tags: ["cloudflare", "dns", "edge", "workers"]
  },
  {
    id: "supabase",
    name: "Supabase",
    provider: "Supabase",
    type: "Database credential",
    category: "Database",
    purpose: "Backend integration",
    useCase: "Prepare optional Postgres, Auth, Storage, Realtime, and Edge Function backend services.",
    riskLevel: "Critical",
    dashboardUrl: "https://supabase.com/dashboard",
    docsUrl: "https://supabase.com/docs",
    scopes: "Project URL, anon key, service role key only for server-side contexts, Edge Function secrets.",
    rotationCadence: "90 days",
    notes: "Never expose a service role key in the static app. Record project owner, environment separation, migration plan, and private secret location.",
    tags: ["supabase", "postgres", "auth", "backend"]
  },
  {
    id: "n8n",
    name: "n8n",
    provider: "n8n",
    type: "Webhook",
    category: "Workflow automation",
    purpose: "Automation workflow",
    useCase: "Track workflow webhooks, credential-backed automations, retries, and handoff paths.",
    riskLevel: "High",
    dashboardUrl: "https://app.n8n.cloud/",
    docsUrl: "https://docs.n8n.io/",
    scopes: "Workflow credentials, webhook URLs, API credentials, retry paths, and downstream app permissions.",
    rotationCadence: "90 days",
    notes: "Record workflow owner, webhook purpose, production/test separation, failure behavior, and credential store location.",
    tags: ["n8n", "webhook", "automation", "workflow"]
  },
  {
    id: "pipedream",
    name: "Pipedream",
    provider: "Pipedream",
    type: "Webhook",
    category: "Workflow automation",
    purpose: "Automation workflow",
    useCase: "Track event-driven workflows, HTTP triggers, connected accounts, and integration prototypes.",
    riskLevel: "High",
    dashboardUrl: "https://pipedream.com/workflows",
    docsUrl: "https://pipedream.com/docs/",
    scopes: "Connected accounts, HTTP trigger URLs, workflow environment variables, OAuth app scopes.",
    rotationCadence: "90 days",
    notes: "Record trigger type, connected accounts, owner, replay behavior, and production endpoint protection.",
    tags: ["pipedream", "webhook", "automation", "oauth"]
  },
  {
    id: "notion",
    name: "Notion",
    provider: "Notion",
    type: "OAuth client",
    category: "Content and CMS",
    purpose: "Data import/export",
    useCase: "Prepare documentation, planning, database sync, redacted report handoff, and knowledge capture.",
    riskLevel: "High",
    dashboardUrl: "https://www.notion.so/",
    docsUrl: "https://developers.notion.com/",
    scopes: "Internal integration token, OAuth scopes, page/database permissions, workspace boundary.",
    rotationCadence: "90 days",
    notes: "Record workspace, database/page IDs, owner, sync purpose, and redacted-only handoff posture.",
    tags: ["notion", "docs", "planning", "knowledge"]
  },
  {
    id: "clickup",
    name: "ClickUp",
    provider: "ClickUp",
    type: "API key",
    category: "Workflow automation",
    purpose: "Automation workflow",
    useCase: "Prepare task creation, implementation planning, status reporting, and project workflow handoffs.",
    riskLevel: "High",
    dashboardUrl: "https://app.clickup.com/",
    docsUrl: "https://developer.clickup.com/",
    scopes: "API token or OAuth scopes, workspace/list IDs, webhook secrets, automation owner.",
    rotationCadence: "90 days",
    notes: "Record workspace, space, folder, list, API owner, webhook use, and redacted evidence handoff rules.",
    tags: ["clickup", "tasks", "project-management", "webhook"]
  },
  {
    id: "playwright",
    name: "Playwright",
    provider: "Microsoft Playwright",
    type: "Other",
    category: "Developer platform",
    purpose: "Development and testing",
    useCase: "Prepare independent browser testing, screenshots, traces, accessibility smoke, and regression labs.",
    riskLevel: "Medium",
    dashboardUrl: "https://playwright.dev/",
    docsUrl: "https://playwright.dev/docs/intro",
    scopes: "Local test fixtures, temporary browser profiles, trace artifact controls.",
    rotationCadence: "Manual",
    notes: "Do not store real vault passwords in traces. Add Playwright only when independent click coverage or screenshots are needed.",
    tags: ["playwright", "testing", "browser", "qa"]
  },
  {
    id: "codex",
    name: "Codex",
    provider: "OpenAI",
    type: "AI model provider",
    category: "AI and machine learning",
    purpose: "Automation workflow",
    useCase: "Prepare repo-aware development, smoke-test execution, implementation planning, and redacted artifact review.",
    riskLevel: "High",
    dashboardUrl: "https://chatgpt.com/codex",
    docsUrl: "https://platform.openai.com/docs",
    scopes: "Workspace permissions, model access, local command permissions, redacted context boundaries.",
    rotationCadence: "Manual",
    notes: "Do not paste real API keys into agent context. Keep AGENTS.md aligned with no-secret and verification rules.",
    tags: ["codex", "ai", "agent", "coding"]
  },
  {
    id: "cursor",
    name: "Cursor",
    provider: "Cursor",
    type: "Other",
    category: "Developer platform",
    purpose: "Development and testing",
    useCase: "Prepare AI-assisted editing, rules, optional MCP connector planning, and local smoke-test loops.",
    riskLevel: "Medium",
    dashboardUrl: "https://cursor.com/",
    docsUrl: "https://docs.cursor.com/",
    scopes: "Workspace trust, rules, optional MCP server credentials stored outside repo.",
    rotationCadence: "Manual",
    notes: "Use .cursor/rules for project constraints. Do not commit real MCP configs or provider tokens.",
    tags: ["cursor", "editor", "mcp", "ai"]
  },
  {
    id: "antigravity",
    name: "Google Antigravity",
    provider: "Google",
    type: "Other",
    category: "Developer platform",
    purpose: "Development and testing",
    useCase: "Prepare agent-first coding handoff, repo instructions, and smoke-test driven implementation loops.",
    riskLevel: "Medium",
    dashboardUrl: "https://antigravity.google/",
    docsUrl: "https://developers.googleblog.com/en/build-with-google-antigravity-our-new-agentic-development-platform/",
    scopes: "Workspace access, agent task context, browser/test permissions, redacted artifact boundaries.",
    rotationCadence: "Manual",
    notes: "Use AGENTS.md and redacted exports for safe agent context. Require smoke and lab evidence after changes.",
    tags: ["antigravity", "google", "ai", "agent"]
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    provider: "Microsoft",
    type: "Other",
    category: "Developer platform",
    purpose: "Development and testing",
    useCase: "Prepare local tasks, recommended extensions, GitHub workflow editing, and static server commands.",
    riskLevel: "Low",
    dashboardUrl: "https://code.visualstudio.com/",
    docsUrl: "https://code.visualstudio.com/docs",
    scopes: "Workspace trust, local tasks, optional extension sign-ins, ignored environment files.",
    rotationCadence: "Manual",
    notes: "Use .vscode tasks for doctor, check, smoke, lab, and full verification. Do not store credentials in workspace settings.",
    tags: ["vscode", "editor", "tasks", "extensions"]
  },
  {
    id: "netlify",
    name: "Netlify",
    provider: "Netlify",
    type: "API key",
    category: "Cloud hosting",
    purpose: "Production application",
    useCase: "Deploy static sites, serverless functions, forms, preview deploys, and environment variables.",
    riskLevel: "High",
    dashboardUrl: "https://app.netlify.com/",
    docsUrl: "https://docs.netlify.com/api/get-started/",
    scopes: "Personal access token, site/team permissions, deploy hooks, environment-variable access.",
    rotationCadence: "90 days",
    notes: "Record team/site owner, deploy hook use, production environment variables, branch deploy policy, and rollback path.",
    tags: ["hosting", "netlify", "deploy", "static"]
  },
  {
    id: "auth0",
    name: "Auth0",
    provider: "Auth0",
    type: "OAuth client",
    category: "Authentication",
    purpose: "User authentication",
    useCase: "Authenticate users, manage OAuth applications, callbacks, logout URLs, and identity provider integrations.",
    riskLevel: "Critical",
    dashboardUrl: "https://manage.auth0.com/",
    docsUrl: "https://auth0.com/docs/get-started/applications",
    scopes: "Client ID/secret, allowed callbacks, allowed origins, tenant settings, management API scopes.",
    rotationCadence: "90 days",
    notes: "Record tenant, application type, callback URLs, logout URLs, allowed origins, MFA policy, and breach response path.",
    tags: ["auth", "oauth", "identity", "users"]
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    provider: "Twilio SendGrid",
    type: "Email/SMS",
    category: "Email and messaging",
    purpose: "Customer messaging",
    useCase: "Send transactional email, notifications, password resets, and deliverability events.",
    riskLevel: "High",
    dashboardUrl: "https://app.sendgrid.com/",
    docsUrl: "https://docs.sendgrid.com/ui/account-and-settings/api-keys",
    scopes: "Restricted mail-send API key, domain authentication, webhook signing, sender identity.",
    rotationCadence: "90 days",
    notes: "Record sender domains, suppression handling, event webhook, privacy purpose, and fallback notification path.",
    tags: ["email", "sendgrid", "messaging", "deliverability"]
  },
  {
    id: "sentry",
    name: "Sentry",
    provider: "Sentry",
    type: "Monitoring",
    category: "Security and compliance",
    purpose: "Monitoring and alerts",
    useCase: "Capture errors, performance traces, release health, and alerting signals.",
    riskLevel: "Medium",
    dashboardUrl: "https://sentry.io/",
    docsUrl: "https://docs.sentry.io/product/accounts/auth-tokens/",
    scopes: "DSN, auth token scopes, project/org access, PII scrubbing settings.",
    rotationCadence: "180 days",
    notes: "Record DSN exposure expectations, PII scrubbing, alert owner, project mapping, and retention settings.",
    tags: ["monitoring", "errors", "observability", "sentry"]
  },
  {
    id: "aws",
    name: "AWS IAM",
    provider: "Amazon Web Services",
    type: "Service account",
    category: "Cloud hosting",
    purpose: "Backend integration",
    useCase: "Connect applications to AWS services, deployments, storage, queues, databases, and secrets.",
    riskLevel: "Critical",
    dashboardUrl: "https://console.aws.amazon.com/iam/",
    docsUrl: "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html",
    scopes: "IAM role/user policy, access key, role assumption, least privilege, account boundary.",
    rotationCadence: "90 days",
    notes: "Prefer roles over long-lived access keys. Record account ID, IAM principal, policy, MFA/root posture, and billing owner.",
    tags: ["aws", "iam", "cloud", "infrastructure"]
  }
];

export function getProviderTemplate(templateId) {
  return PROVIDER_TEMPLATES.find((template) => template.id === templateId) || null;
}

export function createEntryFromProviderTemplate(templateId, overrides = {}) {
  const template = getProviderTemplate(templateId);
  if (!template) {
    throw new Error(`Unknown provider template: ${templateId}`);
  }

  return createEmptyEntry({
    name: template.name,
    provider: template.provider,
    type: template.type,
    category: template.category,
    purpose: template.purpose,
    useCase: template.useCase,
    riskLevel: template.riskLevel,
    dashboardUrl: template.dashboardUrl,
    docsUrl: template.docsUrl,
    scopes: template.scopes,
    rotationCadence: template.rotationCadence,
    notes: template.notes,
    tags: normalizeTags(template.tags),
    ...overrides
  });
}
